// This file is generated by Gemini. For optimal code clarity and maintainability,
// please ensure there are no comments.

'use server';

/**
 * @fileOverview This file contains the Genkit flow for suggesting keywords for a project
 * based on its description and technologies used.
 *
 * - `suggestKeywords` - A function that takes project description and technologies as input
 *   and returns a list of suggested keywords.
 * - `SuggestKeywordsInput` - The input type for the `suggestKeywords` function.
 * - `SuggestKeywordsOutput` - The output type for the `suggestKeywords` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestKeywordsInputSchema = z.object({
  description: z
    .string()
    .describe('The description of the project for which keywords are to be suggested.'),
  technologies: z
    .string()
    .describe('The technologies used in the project, comma separated.'),
});
export type SuggestKeywordsInput = z.infer<typeof SuggestKeywordsInputSchema>;

const SuggestKeywordsOutputSchema = z.object({
  keywords: z
    .array(z.string())
    .describe('An array of suggested keywords for the project.'),
});
export type SuggestKeywordsOutput = z.infer<typeof SuggestKeywordsOutputSchema>;

export async function suggestKeywords(input: SuggestKeywordsInput): Promise<SuggestKeywordsOutput> {
  return suggestKeywordsFlow(input);
}

const suggestKeywordsPrompt = ai.definePrompt({
  name: 'suggestKeywordsPrompt',
  input: {schema: SuggestKeywordsInputSchema},
  output: {schema: SuggestKeywordsOutputSchema},
  prompt: `You are an expert at suggesting keywords for projects.

  Based on the description and technologies used, suggest relevant keywords for the project.
  Return the keywords as a JSON array of strings.

  Description: {{{description}}}
  Technologies: {{{technologies}}}
  `,
});

const suggestKeywordsFlow = ai.defineFlow(
  {
    name: 'suggestKeywordsFlow',
    inputSchema: SuggestKeywordsInputSchema,
    outputSchema: SuggestKeywordsOutputSchema,
  },
  async input => {
    const {output} = await suggestKeywordsPrompt(input);
    return output!;
  }
);
